homme(hubert).
homme(lucien).
homme(david).
homme(jules).
homme(bernard).
homme(gerard).
homme(fabien).
homme(kevin).
homme(alphonse).
homme(cedric).
femme(marie).
femme(zoe).
femme(eloise).
femme(ophelie).
femme(nathalie).
femme(charlotte).
femme(violette).
femme(daniels).
femme(stephanie).
parent(hubert,ophelie).
parent(marie,ophelie).
parent(lucien,gerard).
parent(marie,gerard).
parent(lucien,fabien).
parent(marie,fabien).
parent(david,nathalie).
parent(zoe,nathalie).
parent(jules,charlotte).
parent(zoe,charlotte).
parent(jules,violette).
parent(zoe,violette).
parent(bernard,alphonse).
parent(eloise,alphonse).
parent(fabien,cedric).
parent(nathalie,cedric).
parent(kevin,daniels).
parent(charlotte,daniels).
parent(alphonse,stephanie).
parent(violette,stephanie).
enfant(X,Y):-
parent(Y,X).
fils(X,Y):-
enfant(X,Y),
homme(X).
file(X,Y):-
enfant(X,Y),
femme(X).
mere(X,Y):-
parent(X,Y),
femme(X).
pere(X,Y):-
parent(X,Y),
homme(X).
grand_parent(X,Z):-
parent(X,Y),
parent(Y,Z).
grand_pere(X,Z):-
parent(X,Y),
parent(Y,Z),
homme(X).
grand_mere(X,Z):-
parent(X,Y),
parent(Y,Z),
femme(X).
soeur(X,Y):-
parent(Z,X),
parent(Z,Y),
x\=Y,
femme(X).
frere(X,Y):-
parent(Z,X),
parent(Z,Y),
x\=Y,
homme(X).
oncle(X,Y):-
enfant(Y,Z),
frere(X,Z).
tante(X,Y):-
enfant(Y,Z),
soeur(X,Z).
petite_fille(X,Y):-
grand_parent(Y,X).
ancetre(X,Y):-
parent(X,Y).
ancetre(X,Y):-
ancetre(Z,Y),
parent(X,Z).
